### ISSUE TITLE
几个问题的反馈

### ISSUE THREAD

**Issue by jiangzc** [xymov/vst-video#2]
1.  左侧 ListView 双击条目可以编辑，需要设置成只读属性
2. 全屏之后无法退出，按下esc 右键 等 都没有反应

我的环境：vst-video 2.0 版在 deepin v15 下编译，Qt 版本 5.7.1

**Comment by jiangzc** [comment]
还有一个建议：图标的分辨率很小，放大之后会模糊。可以找稍微大一点的图片 或者用svg 格式的
推荐：
阿里巴巴矢量图标库  https://www.iconfont.cn/  
国外的图标库网站   https://icons8.com/

**Comment by xymov** [comment]
> 1. 顶部ListView双击双击可以编辑，需要设置成初始属性
> 2. 全屏之后无法退出，clickesc快捷等都没有反应
> 
> 我的环境：vst-video 2.0版在deepin v15下编译，Qt版本5.7.1

好的，最新版本已修复

**Comment by xymov** [comment]
> 还有一个建议：图标的分辨率很小，放大之后会模糊。可以找稍微大一点的图片或用svg格式的
> 推荐：
> 阿里巴巴矢量图标库 https://www.iconfont.cn/
> 国外的图标库网站 https://icons8.com/

好的，谢谢提示，会参考的

**Comment by xymov** [comment]
> > 还有一个建议：图标的分辨率很小，放大之后会模糊。可以找稍微大一点的图片或用svg格式的
> > 推荐：
> > 阿里巴巴矢量图标库https://www.iconfont.cn/ 
> > 国外的图标库网站https://icons8.com/
> 
> 好的，谢谢提示，会参考的
